ignore = [".git", "tmp"]

[[actions]]
extensions = [".go"]
command = "go build ."

[[actions]]
files = ["kurogo.toml"]
commands = ["echo 'config file changed'"]

[[actions]]
patterns = ["_test.go"]
commands = ["go test {{.Filename}}"]

[[actions]]
extensions = [".go"]
commands = ["ls", "echo"]
