ignore = [".git", "tmp"]

[[actions]]
extensions = [".go"]
command = "go build ."

[[actions]]
files = ["kurogo.toml"]
command = "echo 'config file changed'"

[[actions]]
patterns = ["_test.go"]
command = "go test {{.Filename}}"
